[package]
name = "claude-code"
version = "0.1.0"
license = "Apache-2.0"
edition = "2024"
description = "Claude Code extension for Zed"


[lib]
path = "src/zed_claude_code.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.5.0"
